spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/lms}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      enabled: true
      max-file-size: 52MB
      max-request-size: 52MB

  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.7
        embedding:
          options:
            model: gemini-embedding-001
            dimensions: 3072
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: lms-documents
        initialize-schema: true

server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET_KEY}

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_S3_REGION:ap-southeast-1}
    bucket: ${AWS_S3_BUCKET}
