spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms
    username: root
    password: 123456
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: vuminh69w@gmail.com
    password: jiul iygk bhev hdsa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      enabled: true
      max-file-size: 52MB
      max-request-size: 52MB

  ai:
    google:
      genai:
        api-key: AIzaSyBWSrmj25eyNsU0-SwQARtRIW2zidjZIxs
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.7
        embedding:
          options:
            model: gemini-embedding-001
            dimensions: 3072
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: lms-documents
        initialize-schema: true

server:
  port: 8080

jwt:
  secret-key: YTJiM2M0ZDVlNmY3ZzhoOWkwajFrMmwzbTRuNW82cDdxOHI5czB0MXUydjN3NHg1eTZ6N0E4QjlDMEQxRTJGM0c0SDVJNko3SzhM

aws:
  s3:
    access-key: AKIAT6GIUGNNJQZUQIIL
    secret-key: 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
    region: ap-southeast-1
    bucket: lms-ttcs
