spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms
    username: root
    password: 123456
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: vuminh69w@gmail.com
    password: jiul iygk bhev hdsa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  port: 8080

jwt:
  secret-key: YTJiM2M0ZDVlNmY3ZzhoOWkwajFrMmwzbTRuNW82cDdxOHI5czB0MXUydjN3NHg1eTZ6N0E4QjlDMEQxRTJGM0c0SDVJNko3SzhM
  